name: ESP32 OTA Build and Upload

on:
  push:
    paths:
      - 'software/esp32_node01/**'
      - 'software/esp32_node02/**'

jobs:
  build_and_upload:
    runs-on: [self-hosted, pi]

    steps:
      - uses: actions/checkout@v3

      - name: Detect changed projects
        id: changes
        run: |
          git fetch origin ${{ github.event.before }} --depth=1 || true
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$changed_files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "changed_node01=false" >> $GITHUB_ENV
          echo "changed_node02=false" >> $GITHUB_ENV

          if echo "$changed_files" | grep -q '^software/esp32_node01/'; then
            echo "changed_node01=true" >> $GITHUB_ENV
          fi
          if echo "$changed_files" | grep -q '^software/esp32_node02/'; then
            echo "changed_node02=true" >> $GITHUB_ENV
          fi

      - name: Build & Upload esp32_node01 (if changed)
        if: env.changed_node01 == 'true'
        run: docker compose -f software/_devices/pi/deploy/downloadESP32/docker-compose-esp32-node01.yml up --build --abort-on-container-exit

      - name: Build & Upload esp32_node02 (if changed)
        if: env.changed_node02 == 'true'
        run: docker compose -f software/_devices/pi/deploy/downloadESP32/docker-compose-esp32-node02.yml up --build --abort-on-container-exit
